### ISSUE TITLE
Avoid having two menus

### ISSUE THREAD

**Issue by agallou** [atoum/extensions.atoum.org#5]
after #4 the website is now usable on mobile, but there is two menu.

for now we were using the same menu than in desktop, it takes all the height. So when some sections like the documentation of the extensions list have a second menu it was difficult to integrate on mobile.

Here is a proposal : 
* on desktop : nothing changes, we keep the same 3 columns layout
* on mobile : on have only one menu, the two menu are merge
** the menu on the primary items appear on the top, with the same order except for the current menu item.
** the current primary menu item, is on the bottom of the primary item list : then we have the secondary menu items.

It will look like this:

![screen shot 2016-12-20 at 00 47 34](https://cloud.githubusercontent.com/assets/320372/21333226/9ec2d31e-c64e-11e6-85be-69c2665631e1.png)

any thoughts on that ? 
@Hywan is that better like that ?

After aproval of the specs here is what we'll have to do
* a PR on the extensions website to use this menu
* make the documentation website responsible and use this menu
* update the menu on the blog

**Comment by Hywan** [comment]
:+1:
It sounds much better. Thank you :-).
